name: CI

on:
  push:
  pull_request:
    - opened
    - edited
    - reopened
    - synchronize

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{secrets.FORESIGHT_API_KEY}}

      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"

      - name: Run build
        run: mvn -B clean install

      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{secrets.FORESIGHT_API_KEY}}
          test_format: JUNIT
          test_framework: JUNIT
          test_path: target/surefire-reports
          coverage_format: JACOCO/XML
          coverage_path: target/jacoco.exec
