name: CI

on:
  push:

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "maven"

      - name: Run build
        run: mvn -B clean install
